### ISSUE TITLE
Credential Type URI definition needed

### ISSUE THREAD

**Issue by Pedro-UwU** [trustoverip/tswg-trust-registry-tf#86]
In the ToIP Trust Registry V1 Specification.md a Credential Type Uri is mentioned but it is not defined anywhere. Is there an URL or resource where this term is defined?

**Comment by darrellodonnell** [comment]
for the v1 specification, this was specifically left undefined as there was no clear definition but a URI could be used by any community that needed it. A DID was envisioned but any valid URI was acceptable.

This remains true still.
